#
# Module manifest for module 'EguibarIT.SecurityPS'
#
# Generated by: Vicente R. Eguibar
#
# Generated on: 23/02/2026
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule           = 'EguibarIT.SecurityPS.psm1'

    # Version number of this module.
    ModuleVersion        = '0.0.1'

    # Supported PSEditions
    CompatiblePSEditions = 'Desktop', 'Core'

    # ID used to uniquely identify this module
    GUID                 = '8c41aca0-580f-4013-86cf-c8b1ac5bbbd7'

    # Author of this module
    Author               = 'Vicente R. Eguibar'

    # Company or vendor of this module
    CompanyName          = 'EguibarIT'

    # Copyright statement for this module
    Copyright            = 'All rights reserved (c) 2026 - EguibarIT.'

    # Description of the functionality provided by this module
    Description          = 'PowerShell module for auditing and remediating Active Directory security vulnerabilities. Focuses on credential theft attacks (Pass-the-Hash, Pass-the-Ticket, Golden/Silver Tickets) as documented in Five Eyes advisories. Supports multi-forest, multi-domain, and hybrid environments.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion    = '5.1'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum .NET Framework version (PowerShell Desktop only)
    # DotNetFrameworkVersion = ''

    # Minimum CLR version (PowerShell Desktop only)
    # ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Required modules
    RequiredModules      = @('ActiveDirectory')

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export
    FunctionsToExport    = @(
        'Find-GPPPasswords',
        'Get-ADASREPRoastingVulnerability',
        'Get-ADKerberoastingPattern',
        'Get-DCSyncAttack',
        'Get-GoldenSAMLDetection',
        'Get-GoldenTicketDetection',
        'Get-MachineAccountQuota',
        'Get-PasswordSprayAttack',
        'Get-SilverTicketDetection',
        'Get-UnconstrainedDelegation',
        'Import-MyModule'
    )

    # Cmdlets to export from this module
    CmdletsToExport      = @()

    # Variables to export from this module
    VariablesToExport    = @('Constants', 'Variables')

    # Aliases to export from this module
    AliasesToExport      = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data and PSData for PowerShell Gallery
    PrivateData          = @{

        PSData = @{

            # Tags for module discovery
            Tags       = @(
                'Windows', 'ActiveDirectory', 'AD', 'Security', 'Audit',
                'CredentialTheft', 'PassTheHash', 'PassTheTicket',
                'GoldenTicket', 'SilverTicket', 'GoldenSAML', 'SAML',
                'ADFS', 'FiveEyes', 'Remediation', 'Compliance',
                'Kerberos', 'NTLM', 'Federation'
            )

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/vreguibar/EguibarIT.SecurityPS/blob/main/LICENSE'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/vreguibar/EguibarIT.SecurityPS'

            # A URL to an icon representing this module.
            IconUri    = 'https://www.eguibarit.com/assets/images/LOGO_SinFondo-180x180.png'

            # ReleaseNotes of this module
            # ReleaseNotes = ''

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}

